export const GET_AUTH_USER = 'GET_AUTH_USER';
export const GET_AUTH_USER_SUCCESS = 'GET_AUTH_USER_SUCCESS';
export const GET_AUTH_USER_FAIL = 'GET_AUTH_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_CHANGE_OPTIONS = 'UPDATE_CHANGE_OPTIONS';

export const CLEAN_MESSAGES = 'CLEAN_MESSAGES';

export const INIT_SUSHI_TYPES = 'INIT_SUSHI_TYPES';
export const INIT_SUSHI_TYPES_SUCCESS = 'INIT_SUSHI_TYPES_SUCCESS';
export const INIT_SUSHI_TYPES_FAIL = 'INIT_SUSHI_TYPES_FAIL';

export const INIT_VEGAN_TYPES = 'INIT_VEGAN_TYPES';
export const INIT_VEGAN_TYPES_SUCCESS = 'INIT_VEGAN_TYPES_SUCCESS';
export const INIT_VEGAN_TYPES_FAIL = 'INIT_VEGAN_TYPES_FAIL';

export const INIT_WOK_TYPES = 'INIT_WOK_TYPES';
export const INIT_WOK_TYPES_SUCCESS = 'INIT_WOK_TYPES_SUCCESS';
export const INIT_WOK_TYPES_FAIL = 'INIT_WOK_TYPES_FAIL';

export const SEARCH_FOR_DISH_TYPE = 'SEARCH_FOR_DISH_TYPE';
export const UPDATE_DISH_TYPES = 'UPDATE_DISH_TYPES';

export const SELECT_DISH = 'SELECT_DISH';
export const HIDE_DISH_MANAGER_MODAL = 'HIDE_DISH_MANAGER_MODAL';

export const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
export const DECREASE_AMOUNT = 'DECREASE_AMOUNT';

export const CONFIRM_SELECTED_DISH = 'CONFIRM_SELECTED_DISH';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const HIDE_NOTFICATION = 'HIDE_NOTFICATION';

export const SHOW_CART = 'SHOW_CART';
export const HIDE_CART = 'HIDE_CART';

export const INCREASE_AMOUNT_AT_CART = 'INCREASE_AMOUNT_AT_CART';
export const DECREASE_AMOUNT_AT_CART = 'DECREASE_AMOUNT_AT_CART';

export const START_LOADING = 'START_LOADING';

export const RENDER_CONTACT_FORM = 'RENDER_CONTACT_FORM';
export const UPDATE_CONTACT_FORM = 'UPDATE_CONTACT_FORM';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';

export const ADD_ORDER_TO_MY_ORDERS = 'ADD_ORDER_TO_MY_ORDERS';

export const INIT_MY_ORDERS = 'INIT_MY_ORDERS';
export const INIT_MY_ORDERS_SUCCESS = 'INIT_MY_ORDERS_SUCCESS';
export const INIT_MY_ORDERS_FAIL = 'INIT_MY_ORDERS_FAIL';

export const ORDER_AGAIN = 'ORDER_AGAIN';
